name: Template CI-CD

on:
  workflow_call:
    secrets:
      AZURE_REGISTRY_USERNAME:
        required: true
      AZURE_REGISTRY_PASSWORD:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el codigo de la aplicacion
        uses: actions/checkout@v4

      # Paso 1: Instalar el SDK usando tu Composite Action granular
      - name: Paso de Infra - Setup .NET
        uses: julio2019vp/mi-infra-templates/.github/actions/dotnet-setup@main

      # Paso 2: Restaurar paquetes usando tu Composite Action granular
      - name: Paso de Infra - Restore NuGet
        uses: julio2019vp/mi-infra-templates/.github/actions/dotnet-restore@main

      # Paso 3: Compilar la app usando tu Composite Action granular
      - name: Paso de Infra - Build nativo
        uses: julio2019vp/mi-infra-templates/.github/actions/dotnet-build@main

  publish-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el codigo para empaquetar
        uses: actions/checkout@v4

      - name: Azure Container Registry Login
        uses: azure/docker-login@v2
        with:
          login-server: miacr.azurecr.io   # <-- Aqui pones la URL de tu Azure Registry
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t miacr.azurecr.io/miapp:latest .
          docker push miacr.azurecr.io/miapp:latest

  deploy:
    needs: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue simulado
        run: echo "Desplegando la imagen de .NET en Azure con exito..."
